# Default values for service-cloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Common Labels
labels:
  app: "admin-api"

# Container Configs
image:
  repository: "chub.cloud.gov.in/service-cloud-dev/admin-middleware"
  pullPolicy: IfNotPresent
  tag: "v120420231852"
replicas: "1"
httpPort: 5000
#resources: |
#  requests:
#    cpu: 100m
#    memory: 256Mi
tracing-enabled: false

env: |
  - name: CONSOLE_PROXY
    value: "https://serviceconsole-prod.cloud.gov.in"
  - name: SMTP_SERVICE_URL
    value: "servicecloud-smtp"
  - name: SMTP_SERVICE_PORT
    value: "25"
  - name: FROM_NAME
    value: "NIC Cloud Services"
  - name: FROM_EMAIL
    value: "noreply@cloud.gov.in"
  - name: FLASK_CONFIG
    value: "production"
  - name: DB_HOST
    value: "postgres-h"
  - name: DB_PORT
    value: "5432"
  - name: POSTGRES_USER
    valueFrom:
      secretKeyRef:
        name: postgres
        key: POSTGRES_USER
  - name: POSTGRES_DB
    valueFrom:
      secretKeyRef:
        name: postgres
        key: POSTGRES_DB
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres
        key: POSTGRES_PASSWORD
  - name: SMS_SERVICE_USERID
    valueFrom:
      secretKeyRef:
        name: sms
        key: SMS_SERVICE_USERID
  - name: SMS_SERVICE_USERPIN
    valueFrom:
      secretKeyRef:
        name: sms
        key: SMS_SERVICE_USERPIN
  - name: NO_PROXY
    value: auth-prod.cloud.gov.in
  - name: OIDC_BASE_URL
    value: https://auth-prod.cloud.gov.in
  - name: OIDC_CLIENT_ID
    value: adminapis
  - name: OIDC_CLIENT_SECRET
    value: yCy4cGO73chatO2gtsZ9bMdXd7U0kVXB
  - name: OIDC_RESOURCE_CHECK_AUD
    value: "true"
  - name: OIDC_DISCOVERY_URI
    value: /auth/realms/cloud/.well-known/openid-configuration
  - name: OIDC_ENABLED
    value: "true"
  - name: MIGRATE_USERS_TO_SSO
    value: "true"
  - name: OIDC_OPENID_REALM
    value: cloud

envFrom: |
  - secretRef:
      name: postgres
      optional: false
  - secretRef:
      name: sms
      optional: false
 
volumes: |
  - name: admin-swagger-ui
    configMap: 
      name: admin-swagger-ui

volumeMounts: |
  - name: admin-swagger-ui
    mountPath: /opt/www/app/templates 


hostAliases:
    - ip: "10.194.98.216"
      hostnames:
      - "auth-prod.cloud.gov.in"  
