apiVersion: v1
kind: Service
metadata:
  name: nks-frontend
  namespace: {{ .Release.Namespace }}
spec:
  ports:
{{- if (eq .Values.global.domain .Values.global.controllerDNSName) }}
  - name: bootstrap
    port: 8030
    targetPort: 8030
    nodePort: 30230
  - name: controller
    port: 8040
    targetPort: 8040
    nodePort: 30240
{{- end }}
  - name: kubectl
    port: 6443
    targetPort: 6443
    nodePort: 31443
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31200
  type: NodePort
  selector:
    io.kompose.service: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: observability-ui
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    kg-app: observability-ui
  type: ClusterIP
