global:
  isDedicatedNamespace: false
  certname: preprod-certs
  #Example labcloud-certs, preprod-certs
frontend:
  labels:
    app: "frontend"

  image:
    repository: "chub.cloud.gov.in/service-cloud-dev/frontend"
    pullPolicy: IfNotPresent
    tag: "v030220231235"
  replicas: "1"
  httpPort: 80

  tracing-enabled: false

  env: |
    - name: VUE_APP_SOCKET_IO
      value: "https://servicesocketio.preprodcloud.nic.in"
    - name: VUE_APP_API_URL
      value: "https://serviceapi.preprodcloud.nic.in"
    - name: VUE_APP_OIDC_AUTH_URL
      value: https://auth.preprodcloud.nic.in/auth
    - name: VUE_APP_OIDC_REALM
      value: cloud
    - name: VUE_APP_OIDC_ENABLED
      value: "false"
    - name: VUE_APP_OIDC_CLIENT_ID
      value: frontend
    - name: VUE_APP_NEW_UI_BTN_LABEL
      value: Switch To New UI
    - name: VUE_APP_NEW_UI_ENABLED
      value: 'true'
    - name: VUE_APP_NEW_UI_URL
      value: https:\/\/service.preprodcloud.nic.in\/      

  volumes: |
    - name: frontendnginx
      configMap:
        name: frontendnginx

  volumeMounts: |
    - name: frontendnginx
      mountPath: /etc/nginx/conf.d

  ingress:
    enabled: true
    hostName: service.preprodcloud.nic.in
    secretName: preprod-certs

react-frontend:
  labels:
    app: "react-frontend"

  # Container Configs
  image:
    repository: "chub.cloud.gov.in/service-cloud-dev/react_frontend"
    pullPolicy: IfNotPresent
    tag: "v10042023161358"
  replicas: "1"
  httpPort: 80
  #resources: |
  #  requests:
  #    cpu: 100m
  #    memory: 256Mi
  tracing-enabled: false

  env: |
    - name: APP_SOCKET_IO
      value: https://servicesocketio.preprodcloud.nic.in
    - name: APP_API_URL
      value: https://serviceapi.preprodcloud.nic.in
    - name: APP_OIDC_AUTH_URL
      value: https://auth.preprodcloud.nic.in/auth
    - name: APP_OIDC_REALM
      value: cloud
    - name: APP_OIDC_ENABLED
      value: 'true'
    - name: APP_OIDC_CLIENT_ID
      value: frontend
    - name: REACT_APP_LINK_GITLAB
      value: https://tracker.cloud.gov.in/
    - name: REACT_APP_LINK_DOCS
      value: https://chub.cloud.gov.in/
    - name: REACT_APP_K8S_DASHBOARD_ENABLED
      value: 'true'
    - name: REACT_APP_OIDC_ENABLED
      value: 'true'
    - name: REACT_APP_OLD_PORTAL_LINK
      value:  https:\/\/service.devcloud.nic.in\/ui\/v1\/
    - name: REACT_APP_ROUTER_BASE_NAME
      value: \/
    - name: REACT_APP_ROUTE_PROXY
      value: 'false'    
    - name: REACT_APP_IS_NKS_ENABLED
      value: 'true'    
    - name: REACT_APP_ADD_NEW_SSL_ACTIVE
      value: 'true'
    - name: REACT_APP_K8S_DASHBOARD_URL
      value: https:\/\/nks.preprodcloud.nic.in          


  volumes: |
    - name: frontendnginxreact
      configMap:
        name: frontendnginxreact

  volumeMounts: |
    - name: frontendnginxreact
      mountPath: /etc/nginx/conf.d

  ingress:
    enabled: true
    hostName: service.preprodcloud.nic.in
    context: 
    secretName: preprod-certs
