apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: middleware-data
spec:
  #storageClassName: {{ .Values.global.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvSize }}
