redis:
  labels:
    app: "redis"

  # Container Configs
  image:
    repository: "coredgeio/redis"
    pullPolicy: IfNotPresent
    tag: "latest"
  replicas: "1"
  httpPort: 6379

  env: |
    - name: ALLOW_EMPTY_PASSWORD
      value: "yes"



redisadmin:
  labels:
    app: "redisadmin"

  # Container Configs
  image:
    repository: "coredgeio/php-redis-admin"
    pullPolicy: IfNotPresent
    tag: "latest"
  replicas: "1"
  httpPort: 80

  env: |
    - name: PHPREDMIN_DATABASE_REDIS_0_HOST
      value: redis    

  ingress:
    enabled: true
    hostName: redisadmin.coredge.io
    context: redis
    secretName: coredge
    ingressClassName: nginx
