{{- define "common.headless-service" -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc_name }}
  annotations:
  labels:
{{- include "common.labels" . | nindent 4 }}
spec:
  selector:
{{- include "common.labels" . | nindent 4 }}
  clusterIP: None
  ports:
  - name: http
    port: {{ .Values.httpPort }}
    targetPort: {{ .Values.httpPort }}
{{- end -}}
