{{- define "common.ingress" -}}
{{- if .Values.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "common.name" . }}
  labels:
{{- include "common.labels" . | nindent 4 }}                            
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostName }}
      secretName: {{ .Values.ingress.secretName }}
  rules:
  - host: {{ .Values.ingress.hostName }}
    http:
      paths:
      - pathType: Prefix
        path: /{{ .Values.ingress.context }}
        backend:
          service:
            name: {{ template "common.name" . }}
            port:
              number: {{ .Values.httpPort }}
{{- end -}} 
{{- end -}} 
