labels:
  app: "nks-postgres"
  group: "db"
namespace: keycloak

image:
  repository: "chub.cloud.gov.in/library/postgres"
  tag: "12_x64"
replicas: "1"
httpPort: 5432

#resources: |
#  requests:
#    cpu: 100m
#    memory: 256Mi

svc_name: "nks-postgres"
pvSize: 50Gi

tracing-enabled: false

env: |
  - name: POSTGRES_USER
    value: api_user
  - name: POSTGRES_PASSWORD
    value: password
  - name: POSTGRES_DB
    value: apidb

volumeMounts: |
  - mountPath: /var/lib/postgresql/
    name: nks-data

volumes: |
  - name: nks-data
    persistentVolumeClaim:
      claimName: nks-data