# Default values for service-cloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Common Labels
labels:
  app: "frontend"

# Container Configs
image:
  repository: "chub.cloud.gov.in/service-cloud-dev/frontend"
  pullPolicy: IfNotPresent
  tag: "v030220231235"
replicas: "1"
httpPort: 80
#resources: |
#  requests:
#    cpu: 100m
#    memory: 256Mi
tracing-enabled: false

env: |
  - name: VUE_APP_SOCKET_IO
    value: "https://socketio-prod.cloud.gov.in"
  - name: VUE_APP_API_URL
    value: "https://serviceapi-prod.cloud.gov.in"
  - name: VUE_APP_OIDC_AUTH_URL
    value: https://auth-prod.cloud.gov.in/auth
  - name: VUE_APP_OIDC_REALM
    value: cloud
  - name: VUE_APP_OIDC_ENABLED
    value: "true"
  - name: VUE_APP_OIDC_CLIENT_ID
    value: frontend

volumes: |
  - name: frontendnginx
    configMap:
      name: frontendnginx

volumeMounts: |
  - name: frontendnginx
    mountPath: /etc/nginx/conf.d

ingress:
  enabled: true
  hostName: service-prod.cloud.gov.in
  context: 

