global:
  isDedicatedNamespace: false
  certname: coredge
  #Example labcloud-certs, preprod-certs
frontend:
  labels:
    app: "frontend"

  image:
    repository: "coredgeio/frontend"
    pullPolicy: IfNotPresent
    tag: "v030220231235"
  replicas: "1"
  httpPort: 80

  tracing-enabled: false

  env: |
    - name: VUE_APP_SOCKET_IO
      value: "https://servicesocketio.coredge.io"
    - name: VUE_APP_API_URL
      value: "https://serviceapi.coredge.io"
    - name: VUE_APP_OIDC_AUTH_URL
      value: https://auth.coredge.io/auth
    - name: VUE_APP_OIDC_REALM
      value: cloud
    - name: VUE_APP_OIDC_ENABLED
      value: "false"
    - name: VUE_APP_OIDC_CLIENT_ID
      value: frontend
    - name: VUE_APP_NEW_UI_BTN_LABEL
      value: Switch To New UI
    - name: VUE_APP_NEW_UI_ENABLED
      value: 'true'
    - name: VUE_APP_NEW_UI_URL
      value: https:\/\/service.coredge.io\/      

  volumes: |
    - name: frontendnginx
      configMap:
        name: frontendnginx

  volumeMounts: |
    - name: frontendnginx
      mountPath: /etc/nginx/conf.d



react-frontend:
  labels:
    app: "react-frontend"

  # Container Configs
  image:
    repository: "coredgeio/react_frontend"
    pullPolicy: IfNotPresent
    tag: "airtel_v1"
  replicas: "1"
  httpPort: 80
  #resources: |
  #  requests:
  #    cpu: 100m
  #    memory: 256Mi
  tracing-enabled: false

  env: |
    - name: APP_SOCKET_IO
      value: https://servicesocketio.coredge.io
    - name: APP_API_URL
      value: https://serviceapi.coredge.io
    - name: APP_OIDC_AUTH_URL
      value: https://auth.coredge.io/auth
    - name: APP_OIDC_REALM
      value: cloud
    - name: APP_OIDC_ENABLED
      value: 'true'
    - name: APP_OIDC_CLIENT_ID
      value: frontend
    - name: REACT_APP_LINK_GITLAB
      value: 
    - name: REACT_APP_LINK_DOCS
      value: 
    - name: REACT_APP_K8S_DASHBOARD_ENABLED
      value: 'true'
    - name: REACT_APP_OIDC_ENABLED
      value: 'true'
    - name: REACT_APP_OLD_PORTAL_LINK
      value:  https:\/\/service.coredge.io\/ui\/v1\/
    - name: REACT_APP_ROUTER_BASE_NAME
      value: \/
    - name: REACT_APP_ROUTE_PROXY
      value: 'false'    
    - name: REACT_APP_IS_NKS_ENABLED
      value: 'true'    
    - name: REACT_APP_ADD_NEW_SSL_ACTIVE
      value: 'true'
    - name: REACT_APP_K8S_DASHBOARD_URL
      value: https:\/\/nks.coredge.io   


  volumes: |
    - name: frontendnginxreact
      configMap:
        name: frontendnginxreact

  volumeMounts: |
    - name: frontendnginxreact
      mountPath: /etc/nginx/conf.d

  ingress:
    ingressClassName: nginx
    enabled: true
    hostName: service.coredge.io
    context: 
    secretName: coredge
