# Default values for service-cloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Common Labels
labels:
  app: "apirevproxy"

# Container Configs
image:
  repository: "chub.cloud.gov.in/service-cloud/apirevproxy"
  pullPolicy: IfNotPresent
  tag: "latest"
replicas: "1"
httpPort: 80
#resources: |
#  requests:
#    cpu: 100m
#    memory: 256Mi
tracing-enabled: false

volumes: |
  - name: apirevproxy
    configMap: 
      name: apirevproxy

volumeMounts: |
  - name: apirevproxy
    mountPath:  /etc/nginx/conf.d/

ingress:
  enabled: true
  hostName: serviceapi-prod.cloud.gov.in
  context: 
  ingressClassName: nginx


