apiVersion: v2
appVersion: 17.0.1-legacy
# Commented since HA postgres will be deployed separately.
dependencies:
  - condition: postgresql.enabled
    name: postgresql-ha
    repository: https://charts.bitnami.com/bitnami
    version: 9.1.0
description: Open Source Identity and Access Management For Modern Applications and Services
home: https://www.keycloak.org/
icon: https://www.keycloak.org/resources/images/keycloak_icon_512px.svg
keywords:
  - sso
  - idm
  - openid connect
  - saml
  - kerberos
  - ldap
maintainers:
  - email: unguiculus@gmail.com
    name: unguiculus
  - email: thomas.darimont+github@gmail.com
    name: thomasdarimont
name: keycloak
sources:
  - https://github.com/codecentric/helm-charts
  - https://github.com/jboss-dockerfiles/keycloak
  - https://github.com/bitnami/charts/tree/master/bitnami/postgresql
version: 18.1.1
