# Default values for service-cloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Common Labels
labels:
  app: "admin"

# Container Configs
image:
  repository: "chub.cloud.gov.in/service-cloud-dev/admin"
  pullPolicy: IfNotPresent
  tag: "v16032023162216"
replicas: "1"
httpPort: 80
#resources: |
#  requests:
#    cpu: 100m
#    memory: 256Mi
tracing-enabled: false
env: |
  - name: VUE_APP_SOCKET_IO
    value: https:\/\/servicesocketio-prod.cloud.gov.in
  - name: VUE_APP_API_URL
    value: https:\/\/serviceapi-prod.cloud.gov.in
  - name: VUE_APP_OIDC_AUTH_URL
    value: https:\/\/auth-prod.cloud.gov.in\/auth
  - name: VUE_APP_OIDC_REALM
    value: cloud
  - name: VUE_APP_OIDC_ENABLED
    value: "true"
  - name: VUE_APP_OIDC_CLIENT_ID
    value: admin-frontend   


volumes: |
  - name: frontendnginx
    configMap:
      name: frontendnginx
volumeMounts: |
  - name: frontendnginx
    mountPath: /etc/nginx/conf.d

ingress:
  enabled: true
  hostName: admin-prod.cloud.gov.in
  context: 
