# Default values for service-cloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Common Labels
labels:
  app: "socketio"

# Container Configs
name: socketio
image:
  repository: "chub.cloud.gov.in/service-cloud-dev/socketio_sso"
  pullPolicy: Always
  tag: "1.2"
replicas: "1"
httpPort: 5000
resources: {}
livenessProbe: |
      failureThreshold: 3
      httpGet:
        path: /
        port: 5000
        scheme: HTTP
      initialDelaySeconds: 20
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 5

readinessProbe: |
      failureThreshold: 3
      httpGet:
        path: /
        port: 5000
        scheme: HTTP
      initialDelaySeconds: 20
      periodSeconds: 30
      successThreshold: 2
      timeoutSeconds: 5

ingress:
  enabled: true
  hostName: socketio-prod.cloud.gov.in
  context:

env: |
  - name: ALLOWED_ORIGIN
    value: ""
