# Default values for egov-finance.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Common Labels
labels:
  app: "pgadmin"

# Container Configs
image:
  repository: "chub.cloud.gov.in/service-cloud/adminer"
  pullPolicy: IfNotPresent
  tag: "latest"
replicas: "1"
httpPort: 8080

env: |
  - name: PGADMIN_DEFAULT_EMAIL
    value: api_user
  - name: PGADMIN_DEFAULT_PASSWORD
    value: ApiUser@01012019
  - name: PGADMIN_LISTEN_ADDRESS
    value: 127.0.0.1
  - name: PGADMIN_LISTEN_PORT
    value: "8080"    

ingress:
  enabled: true
  hostName: servicepgadmin-prod.cloud.gov.in
  context: 

