apiVersion: v1
kind: Service
metadata:
  name: compass-configdb
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
      app: configdb
---
apiVersion: v1
kind: Service
metadata:
  name: configdb
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
      app: configdb
---
apiVersion: v1
kind: Service
metadata:
  name: compass-metricsdb
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
      app: metricsdb
---
apiVersion: v1
kind: Service
metadata:
  name: metricsdb
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
      app: metricsdb
---
apiVersion: v1
kind: Service
metadata:
  name: compass-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: compass-api
spec:
  ports:
    - name: ingress
      port: 8070
      targetPort: 8070
    - name: central-ingress
      port: 8071
      targetPort: 8071
    - port: 6443
      name: kubectl
      targetPort: 6443
    - port: 8060
      name: gateway
      targetPort: 8060
  selector:
    app: compass-api
---
apiVersion: v1
kind: Service
metadata:
  name: compass-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: compass-controller
spec:
  ports:
    - port: 8030
      name: bootstrap
      targetPort: 8030
      protocol: TCP
    - port: 8040
      name: controller
      targetPort: 8040
      protocol: TCP
  selector:
    app: compass-controller
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: compass-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app: compass-controller
spec:
  ports:
    - port: 443
      name: ingress
      targetPort: 6443
      protocol: TCP
  selector:
    app: compass-controller
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: compass-term
  namespace: {{ .Release.Namespace }}
  labels:
    app: compass-term
spec:
  type: ClusterIP
  ports:
    - name: websocket
      port: 8000
      targetPort: 8000
  selector:
    app: compass-term
{{- if .Values.clusterManager.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: compass-cluster-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: compass-cluster-manager
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  selector:
    app: compass-cluster-manager
{{- end }}
