# Default values for service-cloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Common Labels
labels:
  app: "celery"

# Container Configs
image:
  repository: "chub.cloud.gov.in/service-cloud-dev/middleware"
  pullPolicy: IfNotPresent
  tag: "v100420231910"
replicas: "1"
httpPort: 5000
resources: |
  limits:
    cpu: '1'
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 256Mi  
tracing-enabled: false


command:
  - /bin/sh
  - '-cx'
  - >-
    /usr/bin/celery -A app.celery worker --loglevel=INFO >>
    /opt/www/celery.log 2>&1    

env: |
  - name: CONSOLE_PROXY
    value: "https://serviceconsole-prod.cloud.gov.in/postgres-cred"
  - name: POSTGRES_USER
    valueFrom:
      secretKeyRef:
        name: postgres
        key: POSTGRES_USER
  - name: POSTGRES_DB
    valueFrom:
      secretKeyRef:
        name: postgres
        key: POSTGRES_DB
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres
        key: POSTGRES_PASSWORD
  - name: FLASK_CONFIG
    value: "production"
  - name: DB_HOST
    value: "postgres-h"
  - name: DB_PORT
    value: "5432"
  - name: SMS_SERVICE_USERID 
    valueFrom:
      secretKeyRef:
        name: sms
        key: SMS_SERVICE_USERID
  - name: SMS_SERVICE_USERPIN
    valueFrom:
      secretKeyRef:
        name: sms
        key: SMS_SERVICE_USERPIN

envFrom: |
  - secretRef:
      name: postgres
      optional: false
  - secretRef:
      name: sms
      optional: false

