apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-tcp-config
  namespace: {{ .Release.Namespace }}
data:
  default.conf: |-
    server {
        listen     6443;
        proxy_pass compass-api:6443;
    }
    server {
        listen     8030;
        proxy_pass compass-controller:8030;
    }
    server {
        listen     8040;
        proxy_pass compass-controller:8040;
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: {{ .Release.Namespace }}
data:
  default.conf: |-
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }
    server {
        {{- if not .Values.global.ingressEnabled  }}
        listen       80;
        listen       [::]:80;
        {{- else }}
        listen       443 ssl;
        listen       [::]:443 ssl;
        {{- end }}
        server_name  _;
        {{- if .Values.global.ingressEnabled  }}
        ssl_certificate /etc/nginx/certs/ingress/tls.crt;
        ssl_certificate_key /etc/nginx/certs/ingress/tls.key;
        {{- end }}

        proxy_set_header X-Forwarded-For $proxy_protocol_addr; # To forward the original client's IP address
        proxy_set_header X-Forwarded-Proto $scheme; # to forward the  original protocol (HTTP or HTTPS)
        {{- if not .Values.global.ingressEnabled  }}
        proxy_set_header Host $host:31200; # to forward the original host requested by the client
        {{- else }}
        proxy_set_header Host $host; # to forward the original host requested by the client
        {{- end }}

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri /index.html;
        }

        location /auth/resources {
            proxy_pass  http://{{ .Values.global.keycloak_svc_url }};
        }

        location /auth/realms/master {
            deny all;
        }

        location /auth/realms {
            proxy_pass  http://{{ .Values.global.keycloak_svc_url }};
        }

        location /api/kubeguardian/v1 {
            proxy_pass  http://compass-api:8060;
        }

        location /api/cluster-manager {
            proxy_pass  http://compass-api:8060;
        }

        {{- if .Values.global.ingressEnabled  }}
        location /api/compass/v1 {
            rewrite ^/api/compass/v1/(.*) /v1/$1  break;
            proxy_pass  http://compass-api:8060;
        }
        {{- else }}
        location /api/compass {
            rewrite ^/api/compass/(.*) /$1  break;
            proxy_pass  http://compass-api:8060;
        }
        {{- end }}

        location /api/ingress {
            rewrite ^/api/ingress/(.*) /$1  break;
            proxy_pass  http://compass-api:8071;
        }

        location /api/kubeapi {
            rewrite ^/api/kubeapi/(.*) /$1  break;
            proxy_pass  http://compass-api:8070;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }

        location /observability {
            rewrite ^/observability/(.*) /$1  break;
            proxy_pass  http://observability-ui;
        }

        location /ws/terminal {
            rewrite ^/ws/terminal/(.*) /$1  break;
            proxy_pass  http://compass-term:8000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
