apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-frontend
  labels:
    app: react-frontend
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostName }}
      secretName: {{ .Values.ingress.secretName }}
  rules:
    - host: {{ .Values.ingress.hostName }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: react-frontend
                port:
                  number: 80
          - path: /ui/v2/
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 80
