apiVersion: v1
kind: Secret
metadata:
  name: configdb-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: c2lnbWE= # sigma
  password: cGFzc3dvcmQ= # password
---
apiVersion: v1
kind: Secret
metadata:
  name: config-replica-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{ (.Files.Glob "files/auth").AsSecrets | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: controller-certs
  namespace: {{ .Release.Namespace }}
data:
  rootCA.pem: {{ .Values.certs.rootCA.cert }}
  rootCA.key: {{ .Values.certs.rootCA.privKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: api-config-secret
  namespace: {{ .Release.Namespace }}
stringData:
  keycloak.yml: |
    url: https://{{ .Values.global.keycloak_svc_url }}:8443
    realm: {{ .Values.global.realm }}
    {{- if .Values.global.ingressEnabled }}
    domain: {{ .Values.global.domain }}
    {{- end }}
    clientId: controller
    admin:
      username: {{ .Values.controller.username }}
      password: {{ .Values.controller.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
  namespace: {{ .Release.Namespace }}
stringData:
  username: {{ .Values.global.keycloak_username }}
  password: {{ .Values.global.keycloak_password }}
type: Opaque
