apiVersion: v1
kind: Secret
metadata:
  name: vault-snapshot-s3
type: Opaque
data:
  AWS_ACCESS_KEY_ID: VExJMEJPRDNFRlBaODZHVk5UWEY=
  AWS_SECRET_ACCESS_KEY: "dHc2VG1qdlVLRzlmR29kNm5lMnp1Qm1XcHJNUUJzWFk1VnA4VG9adQ=="
  S3_ENDPOINT_URL: 'aHR0cHM6Ly9zdGFhcy1iYnMxLmNsb3VkLmdvdi5pbg=='
