admin:
  labels:
    app: "admin"
  # Container Configs
  image:
    repository: "chub.cloud.gov.in/service-cloud-dev/admin"
    pullPolicy: IfNotPresent
    tag: "v16032023162216"
  replicas: "1"
  httpPort: 80
  #resources: |
  #  requests:
  #    cpu: 100m
  #    memory: 256Mi
  tracing-enabled: false
  env: |
    - name: VUE_APP_SOCKET_IO
      value: https:\/\/servicesocketio.preprodcloud.nic.in
    - name: VUE_APP_API_URL
      value: https:\/\/serviceapi.preprodcloud.nic.in
    - name: VUE_APP_OIDC_AUTH_URL
      value: https:\/\/auth.preprodcloud.nic.in\/auth
    - name: VUE_APP_OIDC_REALM
      value: cloud
    - name: VUE_APP_OIDC_ENABLED
      value: "true"
    - name: VUE_APP_OIDC_CLIENT_ID
      value: admin-frontend   


  volumes: |
    - name: frontendnginx
      configMap:
        name: frontendnginx
  volumeMounts: |
    - name: frontendnginx
      mountPath: /etc/nginx/conf.d

  ingress:
    enabled: true
    hostName: admin.preprodcloud.nic.in
    context: 
    secretName: preprod-certs

admin-new-ui:
  labels:
    app: "admin-new-ui"

  # Container Configs
  image:
    repository: "chub.cloud.gov.in/service-cloud-dev/admin_react_frontend"
    pullPolicy: IfNotPresent
    tag: "v18042023140831"
  replicas: "1"
  httpPort: 80
  #resources: |
  #  requests:
  #    cpu: 100m
  #    memory: 256Mi
  tracing-enabled: false

  env: |
    - name: REACT_APP_API_URL
      value: https://serviceapi.preprodcloud.nic.in
    - name: REACT_APP_SOCKET_IO
      value: https://servicesocketio.preprodcloud.nic.in 
    - name: REACT_APP_OIDC_AUTH_URL
      value: https://auth.preprodcloud.nic.in/auth
    - name: REACT_APP_OIDC_REALM
      value: cloud
    - name: REACT_APP_OIDC_CLIENT_ID
      value: frontend
    - name: REACT_APP_OIDC_ENABLED
      value: 'true'
    - name: REACT_APP_HELP_LINK
      value: ''


  volumes: |
    - name: admin-nginxreact
      configMap:
        name: admin-nginxreact

  volumeMounts: |
    - name: admin-nginxreact
      mountPath: /etc/nginx/conf.d

  ingress:
    enabled: true
    hostName: serviceadmin.preprodcloud.nic.in
    context: 
    secretName: preprod-certs
