apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: csi-cinder-sc-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi