apiVersion: v1
kind: Secret
metadata:
  name: vault-snapshot-agent-token
type: Opaque
data:
  # we use gotmpl here
  # you can replace them with base64-encoded value
  VAULT_APPROLE_ROLE_ID: NmVkOWYxYTEtM2MxNC03YzA4LTU3MTgtNjQ2MmZlZDIyNDZh
  VAULT_APPROLE_SECRET_ID: Y2U0YzU3ZDMtYWVmMS02ZmIwLTc5ZjEtNWVhOWM5OWM2OTNh
